version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
